version: 2

models:

  - name: dim_airports
    columns:
      - name: airport_id
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer
      - name: latitude
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -90
              max_value: 90
      - name: longitude
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -180
              max_value: 180    

  - name: dim_airlines
    columns:
      - name: airline_id
        tests:
          - unique
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: integer

  - name: fct_routes
    columns:

      - name: source_airport_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_airports')
              field: airport_id

      - name: destination_airport_id
        tests:
          - relationships:
              to: ref('dim_airports')
              field: airport_id

      - name: is_direct
        tests:
          - accepted_values:
              values: [true, false]